### ISSUE TITLE
Special.T売れすぎ問題

### ISSUE THREAD

**Issue by Canchu** [Canchu/CoffeeManager#34]

**Comment by Canchu** [comment]
これは、public/javascript/coffeeMarathon.jsの83行目で取ってきていた飲み物のhtmlでの表示名とif分の内容がちがっていたためおきました
この飲み物の名前の対応も、データベースなどで一括管理した方があとあと変更に対応できるので
修正した方がよかとです

**Comment by uhey22e** [comment]
#35 で対応
